FROM ubuntu:20.04
RUN apt-get update && apt-get install -y \
python3 \
python3-pip \
ruby-full \
&& apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip3 install mysql-connector 
COPY dbscripts/ /scripts/
COPY /test/dbtest.py /scripts/
RUN chmod +x /scripts/dbtest.py
COPY entrypoint.sh /scripts/
ENTRYPOINT ["/bin/bash", "/scripts/entrypoint.sh"]